// Authentication
const CONTACT_US_INIT = 'CONTACT_US_INIT';
const CONTACT_US_SUCCESS = 'CONTACT_US_SUCCESS';
const CONTACT_US_ERROR = 'CONTACT_US_ERROR';

// NewsLetter
const SUBSCRIBE_NOW_INIT = 'SUBSCRIBE_NOW_INIT';
const SUBSCRIBE_NOW_SUCCESS = 'SUBSCRIBE_NOW_SUCCESS';
const SUBSCRIBE_NOW_ERROR = 'SUBSCRIBE_NOW_ERROR';

export {
  // Authentication
  CONTACT_US_INIT,
  CONTACT_US_SUCCESS,
  CONTACT_US_ERROR,
  // NewsLetter
  SUBSCRIBE_NOW_INIT,
  SUBSCRIBE_NOW_SUCCESS,
  SUBSCRIBE_NOW_ERROR
};
